pdating prompt, indenting

diff --git a/zsh/bin/wifi-password b/zsh/bin/wifi-password
--- a/zsh/bin/wifi-password
+++ b/zsh/bin/wifi-password
@@ -23,10 +23,10 @@ usage() {
   Usage: wifi-password [options] [ssid]
 
   Options:
-    -q, --quiet      Only output the password.
-    -V, --version    Output version
-    -h, --help       This message.
-    --               End of options
+	-q, --quiet      Only output the password.
+	-V, --version    Output version
+	-h, --help       This message.
+	--               End of options
 
 EOF
 }
@@ -34,17 +34,17 @@ EOF
 # parse options
 while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
   case $1 in
-    -V | --version )
-      echo $version
-      exit
-      ;;
-    -q | --quiet )
-      verbose=
-      ;;
-    -h | --help )
-      usage
-      exit
-      ;;
+	-V | --version )
+	  echo $version
+	  exit
+	  ;;
+	-q | --quiet )
+	  verbose=
+	  ;;
+	-h | --help )
+	  usage
+	  exit
+	  ;;
   esac
   shift
 done
@@ -53,15 +53,15 @@ if [[ "$1" == "--" ]]; then shift; fi
 # merge args for SSIDs with spaces
 args="$@"
 
-# check for user-provided ssid 
+# check for user-provided ssid
 if [ "" != "$args" ]; then
   ssid="$@"
 else
   # get current ssid
   ssid="`$airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'`"
   if [ "$ssid" = "" ]; then
-    echo "ERROR: Could not retrieve current SSID. Are you connected?" >&2
-    exit 1
+	echo "ERROR: Could not retrieve current SSID. Are you connected?" >&2
+	exit 1
   fi
 fi
 
diff --git a/zsh/bin/zdot b/zsh/bin/zdot
--- a/zsh/bin/zdot
+++ b/zsh/bin/zdot
@@ -7,116 +7,116 @@ dot_files=($dot_file_prefix*(N.))
 dots_list=$(print -l ${dot_files:t:r} | cut -d"-" -f 2)
 
 function error_message() {
-    ink -l -c red -t 2 -- "$@"
+	ink -l -c red -t 2 -- "$@"
 }
 
 function success_message() {
-    ink -l -c green -- "$@"
+	ink -l -c green -- "$@"
 }
 
 # Gets the file of a dot name
 function include_dot_file() {
-    local darg="$1"
-    dot_file=(${dot_file_prefix}${darg}*(N.))
-    file_name="${dot_file:t:r}"
-    dot_name="${file_name#dot-}"
+	local darg="$1"
+	dot_file=(${dot_file_prefix}${darg}*(N.))
+	file_name="${dot_file:t:r}"
+	dot_name="${file_name#dot-}"
 }
 
 # Run a specific dot
 function include_dot() {
-    include_dot_file "$1"
+	include_dot_file "$1"
 
-    if [[ ! -f $dot_file ]] {
-        error_message "Error while loading dot $require_dot_arg"
-    }
+	if [[ ! -f $dot_file ]] {
+		error_message "Error while loading dot $require_dot_arg"
+	}
 
-    ink -l -c blue "Running $dot_name dot"
+	ink -l -c blue "Running $dot_name dot"
 
-    $dot_file
+	$dot_file
 
-    local exit_code=$?
-    # Magic exit code for not compatible ones.
-    if (( $exit_code == 34 )) {
-        error_message "$dot_name is not compatible with this system."
-    } elif (( $exit_code != 0 )) {
-        error_message "Error while executing $dot_name"
-        exit 1
-    }
+	local exit_code=$?
+	# Magic exit code for not compatible ones.
+	if (( $exit_code == 34 )) {
+		error_message "$dot_name is not compatible with this system."
+	} elif (( $exit_code != 0 )) {
+		error_message "Error while executing $dot_name"
+		exit 1
+	}
 }
 
 # Include multiple dots
 function include_dots() {
-    # @TODO: async?
-    while (($#)); do
-        include_dot $1
-        (( $+commands[hr] )) && hr ' ' '-=' ' '
-        shift
-    done
+	# @TODO: async?
+	while (($#)); do
+		include_dot $1
+		(( $+commands[hr] )) && hr ' ' '-=' ' '
+		shift
+	done
 }
 
 # Create a dot as a template.
 function create_dot() {
-    local darg=$1
-    include_dot_file $darg
+	local darg=$1
+	include_dot_file $darg
 
-    if [[ -n $dot_name ]] {
-        error_message "Cannot create dot, already exists: $dot_name"
-        exit 1
-    }
+	if [[ -n $dot_name ]] {
+		error_message "Cannot create dot, already exists: $dot_name"
+		exit 1
+	}
 
-    local dot_file="${dot_file_prefix}${darg}"
-    touch $dot_file
-    chmod +x $dot_file
-    success_message "Dot created: '$darg' at '$dot_file'"
+	local dot_file="${dot_file_prefix}${darg}"
+	touch $dot_file
+	chmod +x $dot_file
+	success_message "Dot created: '$darg' at '$dot_file'"
 }
 
 # Run the default dots.
 function default_dots() {
-    # Set OS X defaults
-    # include_dot macos "Running MacOS Defaults dot..."
+	# Set OS X defaults
+	# include_dot macos "Running MacOS Defaults dot..."
 
-    # Install homebrew packages
-    [[ $OSTYPE =~ darwin ]] && include_dot homebrew
+	# Install homebrew packages
+	[[ $OSTYPE =~ darwin ]] && include_dot homebrew
 
-    # Config dot
-    include_dot config
+	# Config dot
+	include_dot config
 
-    # Linix Packages, right now only ubuntu..
-    [[ $OSTYPE =~ linux ]] && include_dot ubuntu
+	# Linix Packages, right now only ubuntu..
+	[[ $OSTYPE =~ linux ]] && include_dot ubuntu
 
-    # Install python packages
-    include_dot python
+	# Install python packages
+	include_dot python
 
-    # Install node packages
-    include_dot node
+	# Install node packages
+	include_dot node
 
-    # Install ruby packages
-    include_dot ruby
+	# Install ruby packages
+	include_dot ruby
 
-    # Install vim packages
-    include_dot vim
+	# Install vim packages
+	include_dot vim
 }
 
 local mode="run"
 while getopts cl opt; do
   case $opt in
-        (l)
-            print -l $dots_list
-            return
-            ;;
-        (c)
-            mode="create"
-            ;;
-    esac
+		(l)
+			print -l $dots_list
+			return
+			;;
+		(c)
+			mode="create"
+			;;
+	esac
 done
 shift $(( OPTIND - 1 ))
 
 if [[ $mode == "run" ]] {
-    if (($#)) {
-        include_dots $*
-    } else {
-        default_dots
-    }
+	if (($#)) {
+		include_dots $*
+	} else {
+		default_dots
+	}
 } elif [[ $mode == "create" ]] {
-    create_dot $*
+	create_dot $*
 }
